name: Backend Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven
    
    - name: Install dependencies and run tests
      run: mvn clean install
      
    - name: Generate Coverage Report
      run: mvn jacoco:report
    
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v2
      with:
        name: backend-coverage-report
        path: target/site/jacoco
